name: Verify PR

on:
  pull_request:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest
    env:
      GOOGLE_DRIVE_FOLDER_ID: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
      GOOGLE_DRIVE_FOLDER_ID_TEST: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID_TEST }}
      GPX_FILES_DIR: gpx-files-real-data
      TRACES_FILE_PATH: traces-real/traces.json

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Authenticate with Google Drive
        run: |
          echo '${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}' > credentials.json

      - name: Install googleapis library
        run: npm install googleapis

      - name: Check Dependabot alerts
        run: npm audit

      - name: Run unit tests
        run: npm test

      - name: Check code coverage
        run: npm run test:coverage

      - name: Upload coverage report to CODECOV
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Run pre-build script
        run: node scripts/run-process-gpx.js

      - name: Build website
        run: npm run build

      - name: Generate documentation
        run: npm run generate-docs
